version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./:/var/www/html:delegated
  mysql:
    image: mysql
    env_file:
      - ./env/mysql.env
    ports:
      - '3306:3306'
    volumes:
      - ./sqldump:/home
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./:/var/www/html
  npm:
    image: node:latest
    working_dir: /var/www/html
    entrypoint: ['npm']
    profiles: ["npm"]
    volumes:
      - ./:/var/www/html
